//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserSurvey.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("835")]
        public int dstOffset {
            get {
                return ((int)(this["dstOffset"]));
            }
            set {
                this["dstOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setReverseAngels {
            get {
                return ((bool)(this["setReverseAngels"]));
            }
            set {
                this["setReverseAngels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0002/0</string>
  <string>0004/0</string>
  <string>0101/1</string>
  <string>010F/0</string>
  <string>0121/1</string>
  <string>0124/100</string>
  <string>0125/25</string>
  <string>0126/0</string>
  <string>012F/202</string>
  <string>0130/20</string>
  <string>0131/20</string>
  <string>0136/0</string>
  <string>0200/30</string>
  <string>0202/5000</string>
  <string>0203/5</string>
  <string>0204/20000</string>
  <string>020A/101</string>
  <string>020B/108</string>
  <string>020D/127</string>
  <string>020E/102</string>
  <string>020F/122</string>
  <string>0210/123</string>
  <string>0211/121</string>
  <string>0219/2</string>
  <string>0220/2</string>
  <string>0224/20</string>
  <string>0306/255</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection srvParametersValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["srvParametersValues"]));
            }
            set {
                this["srvParametersValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MovesNum {
            get {
                return ((int)(this["MovesNum"]));
            }
            set {
                this["MovesNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int intServoRpm {
            get {
                return ((int)(this["intServoRpm"]));
            }
            set {
                this["intServoRpm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string distoLastCOM {
            get {
                return ((string)(this["distoLastCOM"]));
            }
            set {
                this["distoLastCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string servoLastCOM {
            get {
                return ((string)(this["servoLastCOM"]));
            }
            set {
                this["servoLastCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.TreeView projectTree {
            get {
                return ((global::System.Windows.Forms.TreeView)(this["projectTree"]));
            }
            set {
                this["projectTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nisuy")]
        public string nisuyString {
            get {
                return ((string)(this["nisuyString"]));
            }
            set {
                this["nisuyString"] = value;
            }
        }
    }
}
