//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserSurvey.BedekManageWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bedek-online.co.il/", ConfigurationName="BedekManageWebService.ManageServiceSoap")]
    public interface ManageServiceSoap {
        
        // CODEGEN: Generating message contract since element name TryItResult from namespace http://bedek-online.co.il/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bedek-online.co.il/TryIt", ReplyAction="*")]
        LaserSurvey.BedekManageWebService.TryItResponse TryIt(LaserSurvey.BedekManageWebService.TryItRequest request);
        
        // CODEGEN: Generating message contract since element name TreeText from namespace http://bedek-online.co.il/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bedek-online.co.il/GetProjectsTree", ReplyAction="*")]
        LaserSurvey.BedekManageWebService.GetProjectsTreeResponse GetProjectsTree(LaserSurvey.BedekManageWebService.GetProjectsTreeRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://bedek-online.co.il/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bedek-online.co.il/AddNewProblem", ReplyAction="*")]
        LaserSurvey.BedekManageWebService.AddNewProblemResponse AddNewProblem(LaserSurvey.BedekManageWebService.AddNewProblemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryItRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryIt", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.TryItRequestBody Body;
        
        public TryItRequest() {
        }
        
        public TryItRequest(LaserSurvey.BedekManageWebService.TryItRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TryItRequestBody {
        
        public TryItRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TryItResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TryItResponse", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.TryItResponseBody Body;
        
        public TryItResponse() {
        }
        
        public TryItResponse(LaserSurvey.BedekManageWebService.TryItResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bedek-online.co.il/")]
    public partial class TryItResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TryItResult;
        
        public TryItResponseBody() {
        }
        
        public TryItResponseBody(string TryItResult) {
            this.TryItResult = TryItResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectsTree", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.GetProjectsTreeRequestBody Body;
        
        public GetProjectsTreeRequest() {
        }
        
        public GetProjectsTreeRequest(LaserSurvey.BedekManageWebService.GetProjectsTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProjectsTreeRequestBody {
        
        public GetProjectsTreeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProjectsTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProjectsTreeResponse", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.GetProjectsTreeResponseBody Body;
        
        public GetProjectsTreeResponse() {
        }
        
        public GetProjectsTreeResponse(LaserSurvey.BedekManageWebService.GetProjectsTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bedek-online.co.il/")]
    public partial class GetProjectsTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetProjectsTreeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TreeText;
        
        public GetProjectsTreeResponseBody() {
        }
        
        public GetProjectsTreeResponseBody(bool GetProjectsTreeResult, string TreeText) {
            this.GetProjectsTreeResult = GetProjectsTreeResult;
            this.TreeText = TreeText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProblemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProblem", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.AddNewProblemRequestBody Body;
        
        public AddNewProblemRequest() {
        }
        
        public AddNewProblemRequest(LaserSurvey.BedekManageWebService.AddNewProblemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bedek-online.co.il/")]
    public partial class AddNewProblemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int itemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string problemDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reporter;
        
        public AddNewProblemRequestBody() {
        }
        
        public AddNewProblemRequestBody(string tableName, int itemId, string problemDescription, string reporter) {
            this.tableName = tableName;
            this.itemId = itemId;
            this.problemDescription = problemDescription;
            this.reporter = reporter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProblemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProblemResponse", Namespace="http://bedek-online.co.il/", Order=0)]
        public LaserSurvey.BedekManageWebService.AddNewProblemResponseBody Body;
        
        public AddNewProblemResponse() {
        }
        
        public AddNewProblemResponse(LaserSurvey.BedekManageWebService.AddNewProblemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://bedek-online.co.il/")]
    public partial class AddNewProblemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddNewProblemResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int newId;
        
        public AddNewProblemResponseBody() {
        }
        
        public AddNewProblemResponseBody(bool AddNewProblemResult, int newId) {
            this.AddNewProblemResult = AddNewProblemResult;
            this.newId = newId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManageServiceSoapChannel : LaserSurvey.BedekManageWebService.ManageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageServiceSoapClient : System.ServiceModel.ClientBase<LaserSurvey.BedekManageWebService.ManageServiceSoap>, LaserSurvey.BedekManageWebService.ManageServiceSoap {
        
        public ManageServiceSoapClient() {
        }
        
        public ManageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaserSurvey.BedekManageWebService.TryItResponse LaserSurvey.BedekManageWebService.ManageServiceSoap.TryIt(LaserSurvey.BedekManageWebService.TryItRequest request) {
            return base.Channel.TryIt(request);
        }
        
        public string TryIt() {
            LaserSurvey.BedekManageWebService.TryItRequest inValue = new LaserSurvey.BedekManageWebService.TryItRequest();
            inValue.Body = new LaserSurvey.BedekManageWebService.TryItRequestBody();
            LaserSurvey.BedekManageWebService.TryItResponse retVal = ((LaserSurvey.BedekManageWebService.ManageServiceSoap)(this)).TryIt(inValue);
            return retVal.Body.TryItResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaserSurvey.BedekManageWebService.GetProjectsTreeResponse LaserSurvey.BedekManageWebService.ManageServiceSoap.GetProjectsTree(LaserSurvey.BedekManageWebService.GetProjectsTreeRequest request) {
            return base.Channel.GetProjectsTree(request);
        }
        
        public bool GetProjectsTree(out string TreeText) {
            LaserSurvey.BedekManageWebService.GetProjectsTreeRequest inValue = new LaserSurvey.BedekManageWebService.GetProjectsTreeRequest();
            inValue.Body = new LaserSurvey.BedekManageWebService.GetProjectsTreeRequestBody();
            LaserSurvey.BedekManageWebService.GetProjectsTreeResponse retVal = ((LaserSurvey.BedekManageWebService.ManageServiceSoap)(this)).GetProjectsTree(inValue);
            TreeText = retVal.Body.TreeText;
            return retVal.Body.GetProjectsTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaserSurvey.BedekManageWebService.AddNewProblemResponse LaserSurvey.BedekManageWebService.ManageServiceSoap.AddNewProblem(LaserSurvey.BedekManageWebService.AddNewProblemRequest request) {
            return base.Channel.AddNewProblem(request);
        }
        
        public bool AddNewProblem(string tableName, int itemId, string problemDescription, string reporter, out int newId) {
            LaserSurvey.BedekManageWebService.AddNewProblemRequest inValue = new LaserSurvey.BedekManageWebService.AddNewProblemRequest();
            inValue.Body = new LaserSurvey.BedekManageWebService.AddNewProblemRequestBody();
            inValue.Body.tableName = tableName;
            inValue.Body.itemId = itemId;
            inValue.Body.problemDescription = problemDescription;
            inValue.Body.reporter = reporter;
            LaserSurvey.BedekManageWebService.AddNewProblemResponse retVal = ((LaserSurvey.BedekManageWebService.ManageServiceSoap)(this)).AddNewProblem(inValue);
            newId = retVal.Body.newId;
            return retVal.Body.AddNewProblemResult;
        }
    }
}
